### ISSUE TITLE
Chrome/Safari/Firefox - Main Menu formatting isn't identical - see screenshots - make identical to design

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health#1]
Chrome
![screen shot 2017-08-31 at 3 45 07 pm](https://user-images.githubusercontent.com/8631079/29942779-11b6a5d8-8e65-11e7-9e84-d49799f73785.png)

Safari
![screen shot 2017-08-31 at 3 45 18 pm](https://user-images.githubusercontent.com/8631079/29942800-1f189b3c-8e65-11e7-8dec-69dc612ff828.png)

Firefox
![screen shot 2017-08-31 at 3 55 57 pm](https://user-images.githubusercontent.com/8631079/29942831-30432ed6-8e65-11e7-9ed9-adf425871e9d.png)
![screen shot 2017-08-31 at 3 56 10 pm](https://user-images.githubusercontent.com/8631079/29942835-3465ccee-8e65-11e7-80d4-8ea6e260aa6c.png)

**Comment by ccmorris** [comment]
is that only when you are logged in?

**Comment by tgascoigne14** [comment]
This happens when you both logged in and logged out.

**Comment by ccmorris** [comment]
Can you screenshot the issue when logged out in Safari/Chrome

The Firefox screenshots show a separate issue. There is a fixable incompatibility with columns in older Firefox versions.

**Comment by tgascoigne14** [comment]
![screen shot 2017-09-06 at 10 05 03 am](https://user-images.githubusercontent.com/8631079/30116318-34643bba-92eb-11e7-8087-5a3c6a3cf0fb.png)
![screen shot 2017-09-06 at 10 05 30 am](https://user-images.githubusercontent.com/8631079/30116271-1af019e2-92eb-11e7-8c20-2ae6ec20d00d.png)

I'm more concerned with Join Our Team Menu but the Patient, Families, & Visitors is different as well.

![screen shot 2017-09-06 at 10 04 52 am](https://user-images.githubusercontent.com/8631079/30116283-2241c2c2-92eb-11e7-82d2-9e905627fe1b.png)
![screen shot 2017-09-06 at 10 05 48 am](https://user-images.githubusercontent.com/8631079/30116307-2ceb288a-92eb-11e7-97eb-20b69fa2809c.png)

**Comment by ccmorris** [comment]
Change all menu dropdowns to 3 columns except the Programs & Services
