### ISSUE TITLE
Please add the solid blue background as a hover effect

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Bluewater-Health#10]
Employment Opportunities:
![screen shot 2017-09-05 at 10 34 54 am](https://user-images.githubusercontent.com/8989188/30066456-ef5e67e0-9225-11e7-8eb9-c341df0bb902.png)

Volunteering:
![screen shot 2017-09-05 at 10 37 42 am](https://user-images.githubusercontent.com/8989188/30066555-4275dcce-9226-11e7-9fb5-486b4223a6f2.png)

Send an E-Card:
![screen shot 2017-09-05 at 10 50 46 am](https://user-images.githubusercontent.com/8989188/30067176-1587e584-9228-11e7-9b26-d33613a4c234.png)

Publications & Presentations:
![screen shot 2017-09-05 at 10 50 26 am](https://user-images.githubusercontent.com/8989188/30067167-0a17e6e0-9228-11e7-88b4-417936c45b90.png)

**Comment by ccmorris** [comment]
How do you indicate which page is active?

**Comment by ianfader** [comment]
now that you point that out, I think it should remain solid when active but when I hover on the other boxes the background should change to blue.
