### ISSUE TITLE
Volunteer/E-card Form - Add thank you message content

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Bluewater-Health#12]
When submitting the contact form I receive an email and the drupal confirmation message, but when I submit the e-card form and volunteering form I get this:

![screen shot 2017-09-05 at 10 44 05 am](https://user-images.githubusercontent.com/8989188/30066879-3c5eb594-9227-11e7-882a-7ba38c759ee2.png)

**Comment by ccmorris** [comment]
@tgascoigne14 can you please comment on what should be happening here? This needs content either way.

**Comment by tgascoigne14** [comment]
Thanks you message for Volunteering:

Thank you for your interest in volunteering at Bluewater Health. Your application has been received and is being reviewed. If you do not hear from us within 7 business days, please contact Lisa Hendra-Pavey, Manager, Volunteer Resources - lhendra@bluewaterhealth.ca.

**Comment by tgascoigne14** [comment]
Thank you message for E-Card - different message depending on who they are sending it to (patient or staff)

Thank you for taking the time to send a patient/staff member an E-Card. Your card has been received by staff and will be sent to recipient within the next 48 hours.
