### ISSUE TITLE
Firefox - Footer - Footer menu columns not working in Firefox

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health#2]
![screen shot 2017-08-31 at 4 17 00 pm](https://user-images.githubusercontent.com/8631079/29943568-ecdfe370-8e67-11e7-8fcd-cfe62a04aca6.png)

**Comment by ccmorris** [comment]
I don't see this issue in Firefox on my computer. According to my research this issue would only affect Firefox versions before 52. So when this issue is closed please test that it is fixed for you and reopen if not resolved.

**Comment by tgascoigne14** [comment]
@ccmorris I do not see that footer anymore - I tried updating the Firefox browser and it actually said it failed but the footer looks good now. Some mysteries are better left unsolved 💃
