### ISSUE TITLE
News - Unable to add new News article - 500 internal server error

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health#35]
It will not allow me to add the image. See screenshot. I tried to save the page anyway and got the 500 internal error.

![screen shot 2018-01-15 at 2 16 55 pm](https://user-images.githubusercontent.com/8631079/34958191-c6003658-f9fe-11e7-950c-cc85b03bc09e.png)

**Comment by tgascoigne14** [comment]
Update: Was able to add the photo but unable to save the page - gives me 500 internal server error.

**Comment by ccmorris** [comment]
When you choose a file to upload there should be a spinner loading indicator and then a preview of the image when it has completed the upload. Like this:
![screen shot 2018-01-16 at 9 04 18 am](https://user-images.githubusercontent.com/4417748/34992784-467067b6-fa9c-11e7-8417-0ce15f207c2d.png)
Did that not happen?

**Comment by ccmorris** [comment]
Note to self: server error when uploading the image on staging site

**Comment by ccmorris** [comment]
The problem was narrowed down to pasting content from a PDF into the body on Tina's computer.

**Comment by ccmorris** [comment]
I am going to set this to wontfix until there is more information about how this might affect users in the future and what can be done about it.
