### ISSUE TITLE
Footer - Programs & Service sub menu items do not have links

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/Bluewater-Health#9]

**Comment by ccmorris** [comment]
The design had the sub menu links but not the sub sub menu links. Some of the sub menu items are <nolink>s. Should we have all of the sub sub items here? That middle column will be enormous.

**Comment by ianfader** [comment]
@tgascoigne14 each sub menu item should have a content page that the footer menu can link to. I believe that you have requested content for the menu items (Cancer Care & Cardiac Care) that currently do not have content?

**Comment by tgascoigne14** [comment]
@ianfader  Correct - I have requested content for both of those categories so we have the ability to link to all program and services from the footer. I was expecting to receive content for the main categories as well as sub categories so this wouldn't be issue.

@ccmorris Please add links that have active pages and I will add Cancer Care & Cardiac Care when I receive the content.

**Comment by ccmorris** [comment]
@tgascoigne14 you got it
